package com.trading.chartstudio;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/custom-strategies")
public class CustomStrategyController {
    private final JdbcTemplate jdbc;
    private final ObjectMapper json;

    public CustomStrategyController(JdbcTemplate jdbc, ObjectMapper json) {
        this.jdbc = jdbc;
        this.json = json;
        jdbc.execute("CREATE TABLE IF NOT EXISTS custom_strategies (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, config CLOB NOT NULL, created_at TIMESTAMP NOT NULL)");
    }

    @GetMapping
    public List<Strategy> list() {
        return jdbc.query("SELECT id, name, config FROM custom_strategies ORDER BY name", (rs, row) -> new Strategy(rs.getLong("id"), rs.getString("name"), rs.getString("config")));
    }

    @PostMapping
    public ResponseEntity<?> save(@RequestBody SaveRequest request) {
        String name = request.name() == null ? "" : request.name().trim();
        if (name.isBlank() || name.length() > 100) return ResponseEntity.badRequest().body(Map.of("message", "Strategy name must be 1-100 characters."));
        try {
            JsonNode config = json.readTree(request.config());
            if (!config.has("entryConditions") || !config.path("entryConditions").isArray() || config.path("entryConditions").isEmpty()) {
                return ResponseEntity.badRequest().body(Map.of("message", "At least one buy condition is required."));
            }
            jdbc.update("DELETE FROM custom_strategies WHERE name = ?", name);
            jdbc.update("INSERT INTO custom_strategies(name, config, created_at) VALUES (?, ?, ?)", name, json.writeValueAsString(config), Instant.now());
            return ResponseEntity.ok().body(Map.of("message", "Strategy saved."));
        } catch (Exception e) {
            return ResponseEntity.badRequest().body(Map.of("message", "Invalid strategy configuration."));
        }
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable long id) {
        jdbc.update("DELETE FROM custom_strategies WHERE id = ?", id);
        return ResponseEntity.noContent().build();
    }

    public record SaveRequest(String name, String config) {}
    public record Strategy(long id, String name, String config) {}
}
