package com.trading.chartstudio;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.annotation.PostConstruct;
import jakarta.servlet.http.HttpSession;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.Arrays;
import java.util.Base64;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.crypto.Cipher;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.PBEKeySpec;
import javax.crypto.spec.SecretKeySpec;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

/** User accounts plus an encrypted per-user vault of saved broker credentials. */
@Service
public class UserStore {
    private static final Logger log = LoggerFactory.getLogger(UserStore.class);
    private static final SecureRandom RANDOM = new SecureRandom();
    private static final int PBKDF2_ITERATIONS = 210_000;
    private static final int SALT_BYTES = 16;
    private static final int HASH_BYTES = 64;
    private static final int KEY_BYTES = 32;
    private static final int IV_BYTES = 12;

    private final JdbcTemplate jdbc;
    private final ObjectMapper json;

    public UserStore(JdbcTemplate jdbc, ObjectMapper json) {
        this.jdbc = jdbc;
        this.json = json;
    }

    @PostConstruct
    public void init() {
        jdbc.execute("CREATE TABLE IF NOT EXISTS app_users (" +
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
            "username VARCHAR(60) NOT NULL UNIQUE," +
            "password_hash VARCHAR(200) NOT NULL," +
            "salt VARCHAR(64) NOT NULL," +
            "iterations INT NOT NULL," +
            "kek_ciphertext VARCHAR(200) NOT NULL," +
            "created_at TIMESTAMP NOT NULL)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS credential_vaults (" +
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
            "user_id BIGINT NOT NULL," +
            "broker VARCHAR(40) NOT NULL," +
            "name VARCHAR(100) NOT NULL," +
            "data CLOB NOT NULL," +
            "created_at TIMESTAMP NOT NULL," +
            "updated_at TIMESTAMP NOT NULL," +
            "CONSTRAINT uq_vault UNIQUE (user_id, broker, name))");
    }

    public record UserResult(long userId, String username, byte[] dataKey) {}
    public record Profile(long id, String broker, String name, Instant updatedAt) {}
    public record ProfileData(String broker, String name, Map<String, String> data) {}

    public boolean usernameExists(String username) {
        Integer count = jdbc.queryForObject("SELECT COUNT(*) FROM app_users WHERE username = ?", Integer.class, username);
        return count != null && count > 0;
    }

    public UserResult register(String username, char[] password) throws Exception {
        if (usernameExists(username)) throw new IllegalArgumentException("Username already registered.");
        byte[] salt = randomBytes(SALT_BYTES);
        byte[] hash = pbkdf2(password, salt, PBKDF2_ITERATIONS, HASH_BYTES);
        byte[] dataKey = randomBytes(KEY_BYTES);
        byte[] kekCipher = aesEncrypt(pbkdf2(password, salt, PBKDF2_ITERATIONS, KEY_BYTES), dataKey);
        jdbc.update("INSERT INTO app_users(username, password_hash, salt, iterations, kek_ciphertext, created_at) VALUES (?, ?, ?, ?, ?, ?)",
            username, base64(hash), base64(salt), PBKDF2_ITERATIONS, base64(kekCipher), Instant.now());
        long id = jdbc.queryForObject("SELECT id FROM app_users WHERE username = ?", Long.class, username);
        return new UserResult(id, username, dataKey);
    }

    public Optional<UserResult> verifyLogin(String username, char[] password) {
        List<Map<String, Object>> rows = jdbc.queryForList(
            "SELECT id, password_hash, salt, iterations, kek_ciphertext FROM app_users WHERE username = ?", username);
        if (rows.isEmpty()) return Optional.empty();
        Map<String, Object> row = rows.get(0);
        long id = ((Number) row.get("id")).longValue();
        byte[] salt = base64decode((String) row.get("salt"));
        int iterations = ((Number) row.get("iterations")).intValue();
        byte[] attempt = pbkdf2(password, salt, iterations, HASH_BYTES);
        if (!MessageDigest.isEqual(attempt, base64decode((String) row.get("password_hash")))) return Optional.empty();
        try {
            byte[] kekCipher = base64decode((String) row.get("kek_ciphertext"));
            byte[] dataKey = aesDecrypt(pbkdf2(password, salt, iterations, KEY_BYTES), kekCipher);
            return Optional.of(new UserResult(id, username, dataKey));
        } catch (Exception e) {
            log.warn("Could not decrypt data key for user {}", username);
            return Optional.empty();
        }
    }

    public List<Profile> profiles(long userId) {
        return jdbc.query("SELECT id, broker, name, updated_at FROM credential_vaults WHERE user_id = ? ORDER BY broker, name",
            (rs, i) -> new Profile(rs.getLong("id"), rs.getString("broker"), rs.getString("name"),
                rs.getTimestamp("updated_at").toInstant()), userId);
    }

    public void saveProfile(long userId, String broker, String name, Map<String, String> data, byte[] dataKey) throws Exception {
        String cipher = base64(aesEncrypt(dataKey, json.writeValueAsBytes(data)));
        Instant now = Instant.now();
        List<Long> existing = jdbc.query("SELECT id FROM credential_vaults WHERE user_id = ? AND broker = ? AND name = ?",
            (rs, i) -> rs.getLong("id"), userId, broker, name);
        if (existing.isEmpty()) {
            jdbc.update("INSERT INTO credential_vaults(user_id, broker, name, data, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)",
                userId, broker, name, cipher, now, now);
        } else {
            jdbc.update("UPDATE credential_vaults SET data = ?, updated_at = ? WHERE id = ?", cipher, now, existing.get(0));
        }
    }

    public ProfileData getProfile(long userId, long id, byte[] dataKey) {
        List<Map<String, Object>> rows = jdbc.queryForList(
            "SELECT broker, name, data FROM credential_vaults WHERE id = ? AND user_id = ?", id, userId);
        if (rows.isEmpty()) return null;
        try {
            Map<String, Object> row = rows.get(0);
            byte[] cipher = base64decode((String) row.get("data"));
            Map<String, String> data = json.readValue(aesDecrypt(dataKey, cipher), new TypeReference<>() {});
            return new ProfileData((String) row.get("broker"), (String) row.get("name"), data);
        } catch (Exception e) {
            log.warn("Could not decrypt vault profile {}", id);
            return null;
        }
    }

    public void deleteProfile(long userId, long id) {
        jdbc.update("DELETE FROM credential_vaults WHERE id = ? AND user_id = ?", id, userId);
    }

    public static Long currentUserId(HttpSession session) { return (Long) session.getAttribute("account.userId"); }
    public static byte[] currentDataKey(HttpSession session) { return (byte[]) session.getAttribute("account.dataKey"); }
    public static String currentUsername(HttpSession session) { return (String) session.getAttribute("account.username"); }
    public static void login(HttpSession session, UserResult user) {
        session.setAttribute("account.userId", user.userId());
        session.setAttribute("account.username", user.username());
        session.setAttribute("account.dataKey", user.dataKey());
    }
    public static void logout(HttpSession session) {
        session.removeAttribute("account.userId");
        session.removeAttribute("account.username");
        session.removeAttribute("account.dataKey");
    }

    private static byte[] pbkdf2(char[] password, byte[] salt, int iterations, int bytes) {
        try {
            PBEKeySpec spec = new PBEKeySpec(password, salt, iterations, bytes * 8);
            return SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(spec).getEncoded();
        } catch (Exception e) {
            throw new IllegalStateException(e);
        }
    }

    private static byte[] aesEncrypt(byte[] key, byte[] plaintext) throws Exception {
        byte[] iv = randomBytes(IV_BYTES);
        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
        cipher.init(Cipher.ENCRYPT_MODE, new SecretKeySpec(key, "AES"), new GCMParameterSpec(128, iv));
        byte[] ciphertext = cipher.doFinal(plaintext);
        byte[] out = new byte[iv.length + ciphertext.length];
        System.arraycopy(iv, 0, out, 0, iv.length);
        System.arraycopy(ciphertext, 0, out, iv.length, ciphertext.length);
        return out;
    }

    private static byte[] aesDecrypt(byte[] key, byte[] blob) throws Exception {
        byte[] iv = Arrays.copyOfRange(blob, 0, IV_BYTES);
        byte[] ciphertext = Arrays.copyOfRange(blob, IV_BYTES, blob.length);
        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
        cipher.init(Cipher.DECRYPT_MODE, new SecretKeySpec(key, "AES"), new GCMParameterSpec(128, iv));
        return cipher.doFinal(ciphertext);
    }

    private static byte[] randomBytes(int count) {
        byte[] bytes = new byte[count];
        RANDOM.nextBytes(bytes);
        return bytes;
    }
    private static String base64(byte[] bytes) { return Base64.getEncoder().encodeToString(bytes); }
    private static byte[] base64decode(String value) { return Base64.getDecoder().decode(value); }
}
